language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: VD7Y+O45g+JbNUSU2vQKI3SR38y31J1heAMBbhr1hnEM3PMegBLn2v4wqS++u4DaZKHVgz95wY78YzZjyvBCgfgOcCDcG7QvKamfws5IXgpcuz/cfPeUfNE1FInHassJbhvnNf3AjHY9C9RFKp4ujyRUBcSdrBAJgo5qjdQd0PHKGDmSCqSPoaLWi8HJpZQ2X4JSs3JoqAJ9+yxparkNC7mIfSuLTMpnNvQ47VYVH2LKIsT03d8nlGSRXBWBN7j6UZLKvjj24EjFeojMj2ebo2NfgzvmpC9PRgUTCEslQA7Y7mXsnMuF4e1Wc9v121caJZ8DZfasw1Sso91fz2AL9lqlV+GVHXExq9mGjWtyt/WKgRaep4S1bEt5IqHzUb9VBsTCCtuQ4HwTvTVCeTSsK3YrjY2b7potsbnkW+sR/sjNpQ25w68r+7ZckEqo2JGjZr1dr0OE8LYuVaneiYVd8ZOB/C1+7QcbhbiWkMNUSsyzodrZ2RP6SR6owpustonpZmd9Gv+CixCMY/84W8ldXWo9ViglmrYpwuIKR75KNBOHk1xEp9omckxlMtyt40D1KUPAguycOJZCBtFM40jTeXmKwkqgtE26C1Lm8TYRYOUY+qxGowoHO/NpOtR503jG8kWYECFI9xs0hI9nq2laZYYU4pYON4U66OEmHIQ79T4=
  app: pacific-chamber-92677
  on:
    repo: Shubanshii/MusicianShip
